# Generated by Django 3.0.7 on 2020-07-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of Article', max_length=200)),
                ('desc', models.CharField(help_text='Short Description of the Article', max_length=500)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('article_text', models.TextField()),
            ],
        ),
    ]
